version: '3'
services:
    php:
        build:
            context: ./php
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME:?err}-php
        links:
            - 'mariadb'
        volumes:
            - './app:/var/www/html'
            - './.env:/.env'
        depends_on:
            mariadb:
                condition: service_healthy

    nginx:
        image: nginx:alpine
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '80:80'
            - '443:443'
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'
        depends_on:
            - php

    mariadb:
        image: mariadb:11
        container_name: ${APP_NAME:?err}-mariadb
        restart: 'on-failure'
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: yes
            MYSQL_DATABASE: ${DB_DATABASE:?err}
            MYSQL_USER: ${DB_USERNAME:?err}
            MYSQL_PASSWORD: ${DB_PASSWORD:?err}
        volumes:
            - "./data:/var/lib/mysql"
        healthcheck:
            test: ["CMD-SHELL", "healthcheck.sh --connect --innodb_initialized"]
